include conf/machine/sa81x5.conf

MACHINEOVERRIDES =. "sa81x5agl:coqos:"

SERIAL_CONSOLES = "115200;ttyS0"

# Use coqos-qimage bbclass which modifies AVB vbmeta generation.
IMAGE_CLASSES:remove = "qimage"
IMAGE_CLASSES += "coqos-qimage"
