# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

[core]
shell=desktop-shell.so
idle-time=99999999
repaint-window=15
hide-cursor=true

[shell]
locking=true
background-image=/usr/share/weston/qcom_background.png
panel-position=none
