# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

[core]
shell=ivi-shell.so
modules=ivi-controller.so
idle-time=99999999

[shell]
locking=true
# Uncomment below to hide panel
panel-position=none

[ivi-shell]
ivi-input-module=ivi-input-controller.so
ivi-id-agent-module=ivi-id-agent.so

[desktop-app-default]
default-surface-id=20
default-surface-id-max=994967295
