require ${QTI_METAPATH_DISTRO}/conf/distro/auto-agl.conf

PRODUCT = "${MACHINE}"
DEPLOY_NAME_BASE = "${PRODUCT}-automotive"

# Add selinux and related features
DISTRO_FEATURES_append = " acl xattr pam selinux"
PREFERRED_PROVIDER_virtual/refpolicy ?= "refpolicy-minimum"
PREFERRED_VERSION_refpolicy = "2.20190201"
IMAGE_INSTALL_append = " packagegroup-core-selinux"
