require ${QTI_METAPATH_DISTRO}/conf/distro/auto-agl.conf

PRODUCT = "sa81x5agl"

DEPLOY_NAME_BASE = "${@'${MACHINE}' if 'coqos' in d.getVar('MACHINE') else '${PRODUCT}'}-automotive"

# Add selinux and related features
DISTRO_FEATURES_append = " acl xattr pam selinux"
PREFERRED_PROVIDER_virtual/refpolicy ?= "refpolicy-minimum"
PREFERRED_VERSION_refpolicy = "2.20190201"
IMAGE_INSTALL_append = " packagegroup-core-selinux"
