[Unit]
# dnsmasq acts as a DHCP and DNS server on the network interfaces (virtio-tap)
# managed by systemd-networkd. Ensure that systemd-networkd configured those
# interfaces before dnsmasq starts,
# https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/.
BindsTo=sys-devices-virtual-net-virtio\x2dtap.device
After=sys-devices-virtual-net-virtio\x2dtap.device
